### ISSUE TITLE
Validate a prop of type URL

### ISSUE THREAD

**Issue by walleXD** [dwightjack/vue-types#14]
Hi,

Would it be possible to define a custom type which validates the shape as well content. For example using regular expression to validate URL Any thought on how this would be possible?

Thanks in advance

**Comment by dwightjack** [comment]
Hi,

there are a couple of way to create a custom validator:

1) Vue builtin [validator function](
  https://vuejs.org/v2/guide/components.html#Prop-Validation):

```js
var urlType = {
  type: String,  
  validator: function (value) {
    return UrlMatchRegExp.test(value)
  }
};

// later on...
props: {
  url: urlType
}
```

2) VueTypes internal `.custom` type generator:

```js
var urlType = VueTypes.custom(function URLTypeCheck(value) {
  // you need to check here for string
  return typeof value === 'string' && UrlMatchRegExp.test(value)
}, 'You must provide a valid URL')

// later on...
props: {
  url: urlType
}
```

Option 2) uses an internal, undocumented API method (undocumented because it's not as flexible as i'd like), but has the advantage to add both `.def()` and `isRequired` methods/flags as in builtin VueTypes's types.

**Comment by walleXD** [comment]
Thanks a bunch! This is exactly what i needed ...
