### ISSUE TITLE
Validator not works

### ISSUE THREAD

**Issue by patie** [dwightjack/vue-types#207]
Hi,

im trying to use Enum validadator - on compile time, but without success

i tried:

View.vue
```
<some-component fruit="test"></some-component>
```

Fruit.ts
```
export enum Fruit {
    apple = 'apple',
    pear = 'pear'
}
```

Component.vue
```
<script lang="ts">
...
  props: {
    // fruit: string<'apple' | 'pear'>() // no compilation / runtime error
    // fruit: string<Fruit>() // no compilation / runtime error
    // fruit: string<`${Fruit}`>() // no compilation / runtime error
    // fruit: { type: String as PropType<Fruit> } // no compilation / runtime error
    // fruit: oneOf(['apple', 'pear'] as const) // return validation error in console on runtime - ok
  },
...
</script>
```

TS 4.4 / Webpack 5 / Vue 3

any idea where can be problem? thanks!

**Comment by dwightjack** [comment]
Hi, I don't think that typescript supports type checking for single file components at compilation time in any way. 

For example, vue-cli does not report any error at compilation time, because only `.ts` files are checked.

About the examples and runtime error:

- `string<'apple' | 'pear'>()` does not throw at runtime because at runtime this prop converts to `{type: String}` (type information are stripped from complied code).
- `oneOf(['apple', 'pear'] as const)` works because values are validated at runtime.

If you're working with Vue3 and want to have compile-time error reporting I suggest you use https://www.npmjs.com/package/vue-tsc: 

```
npm install vue-tsc -D
npx vue-tsc --noEmit
```

If you're using VSCode, [Volar](https://marketplace.visualstudio.com/items?itemName=johnsoncodehk.volar) can check SFC.

**Comment by dwightjack** [comment]
I am closing this for now. If you have any other comment or issue, feel free to re-open
