### ISSUE TITLE
Question: configs should match?

### ISSUE THREAD

**Issue by Xotic750** [dwightjack/vue-types#25]
Should we have this config line
https://github.com/dwightjack/vue-types/blob/3c80aba0bbfbaf68de88e4be607f524784403b18/karma.conf.js#L44
in
https://github.com/dwightjack/vue-types/blob/3c80aba0bbfbaf68de88e4be607f524784403b18/rollup.config.js#L19
too?

**Comment by dwightjack** [comment]
Hm... I believe that config is only useful when a package uses a node.js core library. Mocha or some other library used in tests use a builtin so is required, but in src we don't use any.
At least that's what I think the option is for

Also since we are building for the browser we cannot use node builtins.

**Comment by Xotic750** [comment]
Ok, just wanted to check. Feel free to close.
