### ISSUE TITLE
Enhancement: Implement browserlist.

### ISSUE THREAD

**Issue by Xotic750** [dwightjack/vue-types#27]
The project that I am working with require a defined set of browsers that a module supports.

I'd like to implement a browser list that meets our minimum requirements. `babel-preset-env` PR https://github.com/dwightjack/vue-types/issues/26 is a pre-requisite to this enhancement.

```
      "targets": {
        "browsers": [
          "last 3 Chrome versions",
          "last 3 Firefox versions",
          "Safari >= 10",
          "Explorer >= 11",
          "Edge >= 12",
          "iOS >= 10",
          "Android >= 6"
        ]
      },
```
Older versions or additional browser can be specified.

It also gives the end user an unequivocal list of browsers that this project supports.

It would be good to include this list in the web site documentation for easy reference.

Refs:
https://github.com/babel/babel/tree/master/packages/babel-preset-env
https://github.com/ai/browserslist
http://browserl.ist/
https://kangax.github.io/compat-table/es6/

**Comment by dwightjack** [comment]
My initial thought about this topic is that since it's a Vue.js library is follows by default the project guidelines on browser compatibility. (You can see a table [here](https://github.com/vuejs/vue))

Anyway it's fine to be more explicit.

Switching to `bable-preset-env` is fine as long as we set the correct browsers as listed on the above link.

If you want you can update your PR with that browsers list before I merge it onto the master branch.

**Comment by dwightjack** [comment]
Ok I got it wrong. From mobile I thought you filed a PR with the new preset. It's an issue instead.

Feel free to create a PR for that, else I'll work on it in the next few days. 😄

**Comment by dwightjack** [comment]
@Xotic750 Added browserlist with v.1.2.0 Opted for a more [conservative list of browsers](https://github.com/dwightjack/vue-types/blob/master/package.json#L80), but every browser version you need in your specification is included.
