### ISSUE TITLE
Question: Clarify es directory

### ISSUE THREAD

**Issue by Xotic750** [dwightjack/vue-types#28]
`dist` contains the `cjs` build, `umd` the `umd` build. What is being produced for the `es` directory?

**Comment by dwightjack** [comment]
Hi,

the `es` folder contains the es6+ version of the library. That version is used by es modules (ie `export { ... }` syntax) aware package bundler like rollup and latest webpack in order to allow es modules related features like tree shaking.  

`es` folder is  referenced on lines [10-11](https://github.com/dwightjack/vue-types/blob/master/package.json#L10) of `package.json`

It differs for `src` in that the source code is transpiled to ES5 since most bundlers configuration exclude `node_modules` folder from babel processing causing issues with uglify and older browsers. [here is the relevant docs](https://github.com/rollup/rollup/wiki/pkg.module#wait-it-just-means-import-and-export--not-other-future-javascript-features) on rollup wiki.

I know some devs are advocating for providing the source code to ES modules aware environment but I think this is more in line with most configuration and won't break anything.

**Comment by Xotic750** [comment]
Thanks for all the feedback and I will get back to looking at this, I'm just very busy with a release deadline at the moment.

**Comment by dwightjack** [comment]
Hi,

no problem. Thank you for your contribution!
