### ISSUE TITLE
Add VueTypes.date validation

### ISSUE THREAD

**Issue by nbgo** [dwightjack/vue-types#3]

**Comment by nbgo** [comment]
`VueTypes.instanceOf(Date)` works, but `VueTypes.date` looks nicer :)

**Comment by dwightjack** [comment]
Hi,

thanks for the suggestion. Are there any other useful type you may suggest?

As a side note, I believe the _Vue way_ is to keep the codebase simple and clean. So for this kind of validation I'd suggest using the build-in format and use VueTypes as an utility to quickly implement required and default flags or more complex validations

```
props: {
    myDate: Date, // just a date
    myRequiredDate: VueTypes.instanceOf(Date).isRequired //a required date
}
```

This will also improve the performance of the validation process because it by-passes the (small) overhead of the VueTypes type generator.

**Comment by nbgo** [comment]
Ok.

**Comment by Mouvedia** [comment]
This should be reopened :
```
var test = new Date("foo");

test.toString()); // 'Invalid Date'
test instanceof Date; // true

**Comment by dwightjack** [comment]
You're right. I thought that Date would have thrown with an invalid date string, but that's not the case. 

Still, I'm not sure it's something that should be added to the core. Could it be the case for an add-on library?

**Comment by Mouvedia** [comment]
An add-on for a plugin ? Seems a bit too much.
We can already do tree-shaking anyway. One extra line won't hurt.

```
// webpack would only include in the bundle what's being imported
import { instanceOf } from 'vue-types';

**Comment by dwightjack** [comment]
My doubt is not about filesize. vue-types is rather small so that's not an issue (by the way, it's exported as a single object so I'm not sure you could do tree-shaking on it).

I'm not sure that such a tye check should be in the core since it's not even in React's prop-types.
If we add a check for `Date` then what about `Promise` or any other JavaScript constructor? 

Maybe a better solution could exposing some utility functions and create a wiki page with instructions and examples on how to add cuatom checks

**Comment by Mouvedia** [comment]
> since it's not even in React's prop-types

I get it. I didn't know it was  inspired by something else.

> or any other JavaScript constructor

Any other constructor wouldn't have that quirk. The user who came looking for a way to validate dates read this issue, like me, probable ended up using `instanceOf`.

> exposing some utility functions

If it's builtin, yeah that would be enough.

**Comment by dwightjack** [comment]
Thanks for the feedback, I'll work of it on the next few days.

About the tree-shaking feature, for some checks I'm using getters ([example](https://github.com/dwightjack/vue-types/blob/master/src/index.js#L12)),  I'm not sure I can expose them the same way with an export. Any suggestions?

**Comment by Mouvedia** [comment]
> Any suggestions?

It seems you could use computed properties and refactor those getters : they all look-alike.
Well maybe not `function/func` and `bool/boolean`, for these you would have to add AKAs.

Anyhow it depends on your goal. Is it parity, readability, lightness ?

**Comment by dwightjack** [comment]
Hi,

I know this is an old standing issue, but with the new [`.extend` method](https://github.com/dwightjack/vue-types#extending-vuetypes) the `date` type can be implemented like this:

```js
VueTypes.extend({
  name: 'date',
  getter: true,
  type: Date,
  validator(value) {
    return (
      Object.prototype.toString.call(value) === '[object Date]' &&
      isFinite(value)
    )
  },
})
```
Usage:

```
props: {
    myDate: VueTypes.date
}
```
