### ISSUE TITLE
`validateType` not working with shim..?

### ISSUE THREAD

**Issue by KnifeFed** [dwightjack/vue-types#319]
I just tried using `validateType` and I have a line that's:

```js
if (!validateType(String, var) || !validateType(oneOf(Object.values(object)), var)) return
```

This works great in dev. 
However, in prod, where I have:

`webpack.prod.conf.js`
```js
resolve: {
    alias: {
        'vue-types': 'vue-types/shim',
    },
}
```

I get `TypeError: Object(...) is not a function` for this line.

**Library version**
5.0.1

**Vue.js version**
2.7.13

**Comment by dwightjack** [comment]
Hello, I published v5.0.2 with a commit that should fix the issue ([source](https://github.com/dwightjack/vue-types/commit/92ff0b5d948c6481b38a2bf69dd4721744e7e603#diff-5bb5e5771ec0adf313c85bb549b172d2948a2ab9f45180b1c4afd4546023caf7R207)). 

Anyway, note that `validateType` and `VueTypes.utils.validate` always return `true` in the shim build, so you should not count on them to return the _correct_ result when using the shim.

**Comment by KnifeFed** [comment]
Thanks for the quick fix! But so when using the shim I won't even get a log message if the value is of the wrong type, it will just send it through and then may or may not error out wherever the value is used?

**Comment by dwightjack** [comment]
@KnifeFed sorry for the late reply. 

> But so when using the shim I won't even get a log message if the value is of the wrong type, it will just send it through and then may or may not error out wherever the value is used?

Yes, that's the same behavior used by Vue when using its production build:
- Vue2: https://github.com/vuejs/vue/blob/main/src/core/util/props.ts#L55-L57
- Vue3: https://github.com/vuejs/core/blob/main/packages/runtime-core/src/componentProps.ts#L602-L605

Basically, prop validation is intended to help during development, if you need to have a persistent validation of data because, for example, it is generated by the user, I guess it's probably better to validate it with a dedicated library like [zod](https://github.com/colinhacks/zod) before passing it to the component.

**Comment by dwightjack** [comment]
I am going to close this issue for now. If you have any other questions or problems feel free to open a new issue.
