### ISSUE TITLE
[Feature Request] Add `.def` support for `shape`

### ISSUE THREAD

**Issue by nolde** [dwightjack/vue-types#32]
It should accept a function that returns an object, just like the `default` prop property from Vue itself.

**Comment by dwightjack** [comment]
Hi I cannot test it right now, but I think that should already be possible.

Custom types like `shape` don't have any sensible default but you can call `def` on them.

Maybe the problem could be that it won't validate a function expecting an obkect instead. 
I will look into it and keep you posted.

Thank you!

**Comment by dwightjack** [comment]
@nolde Checked out this issue. It's already possible to set a default value for `shape` types. Checking at the documentation I think that maybe the following lines could have been misleading:

> You can set shape's types as required but (obviously) you cannot use .def()

That line refers to properties defined in the shape object, not to the object itself. I've updated the documentation to be more explicit on that point. I also updated the underlying logic of `def` to actually clone passed-in objects and arrays in order to act as a real factory function.

**Comment by dwightjack** [comment]
Ah, forgot to mention that all the updates have been published under v1.3.2

**Comment by nolde** [comment]
Sweet, it was that line, in fact, that prompted me to open up the issue.

I'll test it and let you know.

**Comment by dwightjack** [comment]
@nolde closing this issue for now. Feel free to re-open it for further discussion 😄
