### ISSUE TITLE
Ability to extend/overwrite shape definitions

### ISSUE THREAD

**Issue by ymslavov** [dwightjack/vue-types#44]
I'm using VueTypes to implement a Model layer into my application. What I do is something like

    // ItemModel.js
    export default {
         item: VueTypes.shape({
              heading: VueTypes.string.isRequired
         })
     }

then in the component I use it like

    // Item.vue
    import ItemModel from './ItemModel.js'

    ...
    props: {
        inputData: ItemModel
    }

And this works like a charm.

The issue comes when I need to extend or add to the model some props that are only used by a specific version of Item. Optimally I'd like to have something like

    // SpecificVersionOfItem.vue
    import ItemModel from './ItemModel.js'

    ...
    props: {
        inputData: {
               ...ItemModel,
               anotherPropRequiredOnlyByThisComponent: VueTypes.string.isRequired
        }
    }

Is there a way to achieve some sort of extensibility/ability to override already defined props in a shape?

**Comment by dwightjack** [comment]
Hi,

I'm not sure about the final shape of `inputData` definition. I think there's a mistype, because your example will produce something like this:

```js
props: {
    inputData: {
        item: { type: Object, ...}
    }
}
```

Which is not a proper prop definition.

Beside that there's no way to extend  a shape definition. I can think of 2 solutions:

1) place all the definitions you need in a model file, have a shared, extendable object and export the composed variants:

```js
// ItemModel.js
import VueTypes from 'vue-types'

const shared = {
    heading: VueTypes.string.isRequired
    num: VueTypes.number.def(10)
}

export const ItemModel = VueTypes.shape({ // <-- this could even be a default export 
    ...shared,
    anotherProp: VueTypes.string.isRequired
})

export const ItemModel2 = VueTypes.shape({
    ...shared,
    numProp: VueTypes.number
})


// Item.vue
import { ItemModel, ItemModel2 } from './ItemModel.js'

...
props: {
    inputData: ItemModel
    inputData2: ItemModel2
}
```

2) convert `ItemModel` to a function that accepts an object extending the default shape object

```js
// ItemModel.js
import VueTypes from 'vue-types'

export default (props = {}) => VueTypes.shape({
    heading: VueTypes.string.isRequired,
    num: VueTypes.number.def(10)
    ...props
})


// Item.vue
import ItemModel from './ItemModel.js'

...
props: {
    inputData: ItemModel()
    inputData2: ItemModel({
        anotherProp: VueTypes.string.isRequired
    })
}
```

As a side note, also remember that modifiers like `isRequired` and `def` don't return a new type instance, but mutate the current one. So, if in the first solution you run `ItemModel.isRequired` inside a component that prop becomes required everywhere you are using it.

**Comment by dwightjack** [comment]
Hi I'm closing this issue just for housekeeping. Feel free to reopen it if you need more help on this 😄
