### ISSUE TITLE
Default string value within VueTypes.arrayOf(VueTypes.shape({})) not working

### ISSUE THREAD

**Issue by lfkwtz** [dwightjack/vue-types#49]
https://codesandbox.io/s/wq3xprjw28

See example here - any idea why the default string value doesn't resolve?

**Comment by dwightjack** [comment]
Hi that's due to vue internal prop handling. 

Default values apply to just the root level of the prop. In your case you can specify a default value for the array but not for the shape inside the array. 

In the same fashion you can have a default value for a `.shape` prop but not for individual properties of the shape.

On the other hand, validation of required property works properly because vue-types makes the extra job to recursively validate objects.

One way to circumvent this problem is by extracting the elements consuming the shape to its own component and then provide those component `props` value to shape:

```js
const Item = {
  props: {
    name: VueTypes.string.isRequired,
    type: VueTypes.string.def('alien')
  }
}

const List = {
  props: {
    items: VueTypes.arrayOf(
      VueTypes.shape(Item.props).loose
    )
  }
}
```

This way the shape properties are promoted to root level props in `Item` and will receive default values.
