### ISSUE TITLE
PropTypes.bool.default(undefined) not work

### ISSUE THREAD

**Issue by tangjinzhou** [dwightjack/vue-types#71]
```
some: PropTypes.bool.default(undefined) 
```
not work.

this.some is  `false`

and 
```
 createTypes({
  bool: undefined,
})
```

no work

**Comment by dwightjack** [comment]
Hello,

at the moment there is no way to unset the default value for a native type validator except to globally setup it with the `sensibleDefaults` or by creating a custom namespace instance of VueTypes.

Using v2.0.1 on a vue-cli project and with you second example: 

```js
createTypes({
  bool: undefined,
})
```

The returned instance does not have the `default` key for `bool`.

There is one catch, anyway. I have created a [demo sandbox](https://codesandbox.io/s/wild-monad-dk8ii?file=/src/components/HelloWorld.vue) here to showcase it: 

If you notice, the console correctly logs `undefined` for `Types.bool.default`, but Vue renders the `flag` property as `false`.

This is the expected behavior in Vue 2 (boolean props are always coerced to either `false` or `true`). That's changed in Vue 3 so I guess though.

**Comment by tangjinzhou** [comment]
Now I have to  use ` { type: Boolean, default: undefined } ` instead of Types.bool.

**Comment by dwightjack** [comment]
While I think that's somehow an unconventional use of a boolean prop, you can extend VueTypes with a custom type like this:

```js
import VueTypes from "vue-types";

// Add VueTypes.looseBool
export default VueTypes.extend([
  {
    name: "looseBool",
    getter: true,
    type: Boolean,
    default: undefined
  }
]);
```
Documentation: https://dwightjack.github.io/vue-types/advanced/extending-vue-types.html#the-extend-method
Example sandbox: https://codesandbox.io/s/wild-monad-dk8ii?file=/src/types.js

**Comment by tangjinzhou** [comment]
`Types.oneOfType([Types.looseBool, Types.string])`  still `false`

https://codesandbox.io/s/twilight-sun-pmoox?file=/src/components/HelloWorld.vue

**Comment by dwightjack** [comment]
So, that's another kind of issue. The `oneOfType` accounts just for the type and validator of each type, so the resulting prop validator is:

```js
{ type: [Boolean, String] }
```

The solution is again to create a custom type: 

```
export default VueTypes.extend([
  {
    name: "myType",
    getter: true,
    type: [Boolean, String],
    default: undefined
  }
]);
```

or maybe create an utility function to wrap the type:

```js
function withUndefined(type) {
  type.default = undefined
  return type
}

//


```
withUndefined(Types.oneOfType([Types.looseBool, Types.string]))
```

**Comment by tangjinzhou** [comment]
Thank you for your help.  
vue-types is very cool.
I will refactor [ant-design vue](https://github.com/vueComponent/ant-design-vue) use it.
In fact, It is also used in ant-design-vue 1.x version.

**Comment by dwightjack** [comment]
Thank you. 😃 
Feel free to ping me if you find any other issue.

Just to be sure: note that if the library is going to use vue3 you need to use `vue-types@3` (also under the `vue3` tag on npm). APIs are the same but it accounts for some missing Vue globals and different Typescript notations.

**Comment by danranVm** [comment]
I overwrite the definition of  `vue-types` with a type assertion

```ts
export class PropTypes extends VueTypes {
  // see https://github.com/dwightjack/vue-types/issues/71
  static get bool(): VueTypeValidableDef<boolean> & { default: boolean } {
    return toValidableType('bool', {
      type: Boolean,
      default: undefined,
    }) as VueTypeValidableDef<boolean> & { default: boolean }
  }
}
```
