### ISSUE TITLE
PropTypes.string should not be required property in TS

### ISSUE THREAD

**Issue by Amour1688** [dwightjack/vue-types#72]
![image](https://user-images.githubusercontent.com/31695475/96535323-1c24dd00-12c4-11eb-9fe6-fdee69f6d44d.png)

**Comment by dwightjack** [comment]
Hi, 

I think the result you're getting is related to how `RequiredKeys` (used in `ExtractPropTypes`) works: it looks for `required` or `default` properties defined on the prop definition. Since `VueTypes.string` comes with a default value of `''` is is considered required.

If you want to generated a prop validator without default you can use the `string` named export function. See here for an example: https://codesandbox.io/s/lucid-sound-cchj7?file=/src/typeDemo.ts
