### ISSUE TITLE
@vue/composition-api props type error

### ISSUE THREAD

**Issue by djkloop** [dwightjack/vue-types#86]
```js
// shims-tsx.d.ts

import Vue, { VNode } from "vue";
import { ComponentRenderProxy } from "@vue/composition-api";
declare global {
  namespace JSX {
    // tslint:disable no-empty-interface
    interface Element extends VNode {}
    // tslint:disable no-empty-interface
    interface ElementClass extends ComponentRenderProxy {}
    interface ElementAttributesProperty {
      $props: any; // specify the property name to use
    }
    interface IntrinsicElements {
      [elem: string]: any;
    }
  }

  interface ImportMeta {
    env: Record<any, string>;
  }
}

```
```js

import VueTypes from 'vue-types';
import { defineComponent } from "vue-demi";

const TimerProps = {
  count: VueTypes.number.def(111)
}

export default defineComponent({
  name: "Timer",
  props: TimerProps,
  setup(props) {
    return () => <div>Timer组件 -> { props.count }</div>;
  },
});


```
![image](https://user-images.githubusercontent.com/21050914/120449265-dc79b400-c3c1-11eb-9f1e-8a554b51dd60.png)

**Comment by dwightjack** [comment]
Hi,

it might be some incompatibility with vue-demi. At the moment vue@3 requires vue-types@3 and vue@2 requires vue-types@2. This is needed because props Typescript definition has changed in vue@3.

I am working on an unified version, though. If you want to try it out you can install it by running `npm i vue-types@4.0.0-rc.2` or `npm i vue-types@next`.

**Comment by djkloop** [comment]
@dwightjack Works well, thanks for reply

**Comment by djkloop** [comment]
@dwightjack 

https://github.com/dwightjack/vue-types/blob/5ffb6204c20d17793a65c7f6822d3e8d71341a61/src/sensibles.ts#L6

The default value here cannot be an empty string, right? If the user passes in an undefined, it will be judged wrong

![image](https://user-images.githubusercontent.com/21050914/120598737-39847100-c479-11eb-829d-6f342fa3fd64.png)

![image](https://user-images.githubusercontent.com/21050914/120598997-86684780-c479-11eb-801c-ea12600b0e2f.png)

**Comment by dwightjack** [comment]
I think that, since you're passing `undefined` (<Component title={undefined} />), it's like you are not passing the prop and so `props.title` uses its default value (empty string).

If you need to manage `undefined` as prop value, you can reset the prop default ([source](https://github.com/dwightjack/vue-types/blob/unified-version/src/utils.ts#L274-L278)):

```ts
const TimerComponentProps = {
  title: VueTypes.string.def(undefined) 
}
```

In this case, `props.title ?? 'a string'` will print `a string`.

**Comment by djkloop** [comment]
emmm....This works too.. thanks for reply

**Comment by dwightjack** [comment]
Great!

I have opened an issue to improve the documentation regarding the usage of `.def(undefined)` because I think it's not clear enough.

I am going to close this issue. Feel free to open a new issue if you need support or if you encounter any other problem 😄.
